<?xml version="1.0" encoding="UTF-8"?><testsuite errors="1" failures="0" name="RETO AUTOMATIZACION" skipped="0" tests="1" time="36.45" timestamp="2025-04-01 01:05:12"><testcase name="Reto Practico QA Automatizador"><error message="The following error occurred: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:47372&#10;Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'&#10;System info: host: 'PE-HO-451', ip: '192.168.80.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_342'&#10;Driver info: driver.version: RemoteWebDriver" type="org.openqa.selenium.WebDriverException">The following error occurred: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:47372
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'PE-HO-451', ip: '192.168.80.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_342'
Driver info: driver.version: RemoteWebDriver</error><system-err>The following error occurred: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:47372
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'PE-HO-451', ip: '192.168.80.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_342'
Driver info: driver.version: RemoteWebDriver&#13;
co.com.fsfb.taks.DiligenciarReto.performAs(DiligenciarReto.java:39)&#13;
co.com.fsfb.stepDefinitions.DiligenciarRetoAutomatizacion.el_usuario_ingresa_en_el_sistema(DiligenciarRetoAutomatizacion.java:30)&#13;
cucumber.runner.Runner.runPickle(Runner.java:80)&#13;
worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)&#13;
worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)&#13;
</system-err></testcase></testsuite>